### ISSUE TITLE
Announcements not working anymore

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#181] opened 2015-09-26 16:37 UTC
I've tried to set up a company announcement here https://www.thegooddata.org/achievements/create but when saving I got an error 500

**Comment by JuanMenendezBuitrago** [comment] 2015-09-26 17:48
I know I am not the asignee but since I see this is urgent .... the problem is in the definition of the field "id" in the tbl_achievements. This field is defined as being of type "character" instead of type "integer", therefore the following code in the model `Achievements` doesn't work as expected because `max(id)` returns '9' instead of '10':

```php
          // set automatically a new id
          if (!$this->id) {
            $max_id=Yii::app()->db->createCommand("SELECT max(id) FROM {{achievements}}")->queryScalar();

            if ($max_id) {
              $max_id++;
            } else {
              $max_id=1;
            }
            $this->id=$max_id;
          }
```

**Comment by atrandafir** [comment] 2015-09-26 17:50
Hi @JuanMenendezBuitrago I was just going to look into it. I see what you say. Let me know if you want to try to solve it or if I can do it and then try to deploy.

**Comment by JuanMenendezBuitrago** [comment] 2015-09-26 17:52
I have to leave right now so if you can solve it really quick...

**Comment by atrandafir** [comment] 2015-09-26 17:56
OK I'm looking into this to solve is as quick as possible.

**Comment by atrandafir** [comment] 2015-09-26 18:10
Okay this has been fixed with a quick solution. Indeed the type of ID field is wrong. It should auto increment. But to not have to change db structure right now and provide a quick solution I've just casted the field as integer and it returns the correct max value.

Thank you @JuanMenendezBuitrago for pointing this out.

**Closed by atrandafir** 2015-09-26 18:10 UTC
Labels: prio:urgent, status:in development, type:bug
